#ifndef CTE_Definitions_H
#define CTE_Definitions_H

namespace CTE {

#define nil nullptr
#define neg -1

using Void = void;

using Bool = bool;

using Sym = char;

using Byte = unsigned char;
using Byte8 = unsigned char;
using Byte16 = unsigned short int;
using Byte32 = unsigned int;
using Byte64 = unsigned long int;

using Int = signed int;
using Int8 = signed char;
using Int16 = signed short int;
using Int32 = signed int;
using Int64 = signed long int;

using Nat = unsigned int;
using Nat8 = unsigned char;
using Nat16 = unsigned short int;
using Nat32 = unsigned int;
using Nat64 = unsigned long int;

using Real = double;
using Real32 = float;
using Real64 = double;

}

#endif // CTE_Definitions_H
